version: "3.9"
# DAGSTER PROJECT
services:
  dagster_elt:
    restart: always
    container_name: dagster_elt_demo
    build:
      context: .
      dockerfile: ./Dockerfile_Dagster
    ports:
      - 4000:3000
    volumes:
      - .:/opt/dagster/app
    networks:
      - elt_network

  # SQLSERVER
  sqlserver_source:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    container_name: sqlserver_source
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - elt_network

  # POSTGRESQL
  postgres_target:
    image: postgres:11
    restart: always
    shm_size: 128mb
    container_name: postgres_target
    environment:
      POSTGRES_PASSWORD: Admin456
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/data:/var/lib/postgresql/data
    networks:
      - elt_network

volumes:
  mssql_data:
  pg_data:

networks:
  elt_network:
    driver: bridge
