demo_transformations:
  outputs:
    dev:
      dbname: "{{ env_var('PG_DATABASE') }}"
      host: "{{ env_var('PG_HOST') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      port: "{{ env_var('PG_PORT') | int }}"
      schema: "{{ env_var('PG_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('PG_USER') }}"
  target: dev